pipeline {
    agent any

    environment {
        PYTHONUNBUFFERED = "1"
    }

    stages {

        stage('Setup Python Environment') {
            steps {
                sh '''
                    python3 -m venv venv

                    . venv/bin/activate

                    pip install --upgrade pip

                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Parallel Tests') {
            steps {
                sh '''
                    . venv/bin/activate

                    pytest tests/test_parallel_demo.py -n 2 --alluredir=allure-results
                '''
            }
        }

        stage('Generate Allure Report') {
            steps {
                allure([
                    includeProperties: false,
                    jdk: '',
                    results: [[path: 'allure-results']]
                ])
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'allure-results/**', allowEmptyArchive: true
        }
    }
}