pipeline {

    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'python -m venv venv'
                bat 'venv\\Scripts\\pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'venv\\Scripts\\pytest -n 3 --alluredir=reports/allure-results'
            }
        }

        stage('Generate Allure Report') {
            steps {
                bat 'allure generate reports/allure-results -o reports/allure-report --clean'
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'reports/**, screenshots/**'
            }
        }
    }
}